version: '3.8'

services:
  dev:
    build:
      dockerfile: docker/Dockerfile
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "./docker/dev-entrypoint.sh:/root/entrypoint.sh"
    entrypoint: ["/root/entrypoint.sh"]
    ports:
      - "3000:3000"
    networks:
      wallet-accountant_wallet-accountant:
        aliases:
          - wallet-accountant-ui

networks:
  wallet-accountant_wallet-accountant:
    external: true
